### ISSUE TITLE
Add subscribe button for search result

### ISSUE THREAD

**Issue by hetong007** [fanfoujs/xiaofan#57]
- Xiaofan version: 1.10.4
- Operating system: Android 9

### Expected behavior

I search for a keyword, and get a list of messages containing the keywords, without any side effects.

### Actual behavior

I search one keyword, and then I am automatically subscribed to all messages containing this keyword. This is not expected.

Everytime I searched something with the app, I need to visit the website and unsubscribe every word that I have searched, which makes me nervous to search for anything with this app.

**Comment by LitoMore** [comment]
Any comments @fanfoujs/xiaofan-team ?
